# Generated by Django 5.0 on 2024-03-11 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='message_file',
        ),
        migrations.AddField(
            model_name='message',
            name='description',
            field=models.TextField(blank=True, max_length=10000, verbose_name='description'),
        ),
    ]
