# Generated by Django 5.0 on 2024-03-12 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_remove_chat_receiver_remove_chat_sender_chat_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='is_private',
        ),
    ]
