# Generated by Django 5.0 on 2024-03-12 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_remove_chat_is_private'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='private chat'),
        ),
        migrations.AddField(
            model_name='chat',
            name='participants',
            field=models.ManyToManyField(related_name='chats', to=settings.AUTH_USER_MODEL, verbose_name='participants'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_chats', to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
    ]
