# Generated by Django 5.0 on 2024-03-12 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_chat_is_private_chat_participants_alter_chat_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='is_private',
            field=models.BooleanField(default=True, verbose_name='private chat'),
        ),
    ]
