# Generated by Django 5.0 on 2024-03-12 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0008_alter_chat_is_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='private chat'),
        ),
    ]
