# Generated by Django 5.0 on 2024-03-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0011_remove_chat_participants_chat_receiver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='title',
            field=models.CharField(db_index=True, max_length=25, verbose_name='name of the chat'),
        ),
    ]
