# Generated by Django 5.0 on 2024-03-14 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0014_remove_chat_receiver_owner_chat_receiver_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chats', to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='receiver',
            field=models.ManyToManyField(related_name='my_chats', to=settings.AUTH_USER_MODEL, verbose_name='receiver'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='receiver_owner',
            field=models.ManyToManyField(related_name='my_own_chats', to=settings.AUTH_USER_MODEL, verbose_name='receiver_owner'),
        ),
    ]
