# Generated by Django 5.0 on 2024-03-14 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0015_alter_chat_owner_alter_chat_receiver_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='receiver_owner',
        ),
        migrations.AddField(
            model_name='chat',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_chats', to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='receiver',
            field=models.ManyToManyField(related_name='received_chats', to=settings.AUTH_USER_MODEL, verbose_name='receiver'),
        ),
    ]
