# Generated by Django 5.0 on 2024-03-15 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0017_remove_chat_receiver_chat_receiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='description',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='title',
            field=models.CharField(db_index=True, max_length=25, null=True, verbose_name='name of the chat'),
        ),
    ]
