# Generated by Django 5.0 on 2024-03-11 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={},
        ),
        migrations.RemoveField(
            model_name='board',
            name='description',
        ),
        migrations.RemoveField(
            model_name='board',
            name='name',
        ),
        migrations.RemoveField(
            model_name='board',
            name='owner',
        ),
        migrations.AddField(
            model_name='board',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='board_images/', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='board',
            name='sub_title',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='sub_name of the image'),
        ),
        migrations.AddField(
            model_name='board',
            name='title',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='name of the image'),
        ),
    ]
