# Generated by Django 5.0 on 2024-03-10 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_alter_post_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(db_index=True, default='Anonymous', max_length=70, verbose_name='name of the comment'),
        ),
    ]
